### ISSUE TITLE
シナリオの進行状況をwebhookで通知したい

### ISSUE THREAD

**Issue by suwa-sh** [scenario-test-framework/stfw#1]
### ストーリー
利用者 として
シナリオの進行状況を外部システムに連携 するために、
webhookで通知 できる。

### 背景・経緯
cliなので、起動は各種CIシステムに任せられる。
複数環境でのシナリオ進行状況の可視化や、実行結果の解析などを考えると
run|scenario|bizdate|process ごとに、状況と結果を通知したい。

通知先は、利用者が自由に決めたい。
通知イベントは、start|cancel|success|error で、ON/OFFを設定したい。
通知内容は、run|scenario|bizdate は固定で定義できるが、processはpluginごとに拡張したい。

### 受け入れ条件
1. **stfw.yml で url群 | eventを設定 できること**
travisのAPIに揃える。
が、ステータスの履歴管理はdigdagに移譲しているので、changeは取れない。ON|OFF のみ。
```yaml
  webhooks:
    urls:
      - http://hooks.mydomain.com/AAA
      - http://hooks.mydomain.com/BBB
    on_start: true
    on_cancel: false
    on_success: true
    on_error: true
```
2. **payloadはtemplateファイルで変更 できること**
「run / scenario / bizdate / process 全ての共通」
「run | scenario | bizdate | process-plugin共通 のそれぞれ」
「process-plugin毎」
にtemplateファイルをyamlで用意。
templateを組み合わせて送信時のpayload templateを作成。
yamlの環境数部分を展開して送信。
　
3. **送信は非同期で、エラーでも後続処理を続行 できること**
シナリオとは関係ないので処理時間、実行結果に影響を出したくない。
embedded setup / teardown で、POSTリクエストをバックグラウンド実行。
リクエストの実行結果は、ログファイル出力のみ。

### 対応詳細
1. payload: 「run / scenario / bizdate / process 全ての共通」
```yaml
payload:
  id: ${run_id}[+${scenario_name}+${bizdate_dirname}+${process_dirname}]
  type: run|scenario|bizdate|process
  status: started|canceled|success|error
  start time: YYYY-MM-DD HH:mm:ssZ
  end time: YYYY-MM-DD HH:mm:ssZ|null
  processing time: HH:mm:ss|null
  stfw:
    host: 100.100.100.100
    user: $(whoami)
    home: ${STFW_HOME}
    version: ${STFW_VERSION}
    digdag url: ${STFW_SERVER_URL}
    digdag version: ${STFW_SERVER_VERSION}
    project home: ${STFW_PROJ_HOME}
    project version: ${STFW_PROJ_VERSION}
```
2. payload: run
```yaml
---
#payload:
  run:
    run id: ${stfw_run_id}
    workspace dir: ${stfw_run_workspace}
    params: ${stfw_run_params}
```
3. payload: scenario
```yaml
---
#payload:
#  run:
    scenario:
      name: ${stfw_scenario_name}
```
4. payload: bizdate
```yaml
---
#payload:
#  run:
#    scenario:
      bizdate:
        dirname: ${stfw_bizdate_dirname}
        seq: ${stfw_bizdate_seq}
        bizdate: ${stfw_bizdate}
```
5. payload: process-plugin共通
```yaml
---
#payload:
#  run:
#    scenario:
#      bizdate:
        process:
          dirname: ${stfw_process_dirname}
          seq: ${stfw_process_seq}
          group: ${stfw_process_group}
```
6. payload: process-plugin.scripts
```yaml
---
#payload:
#  run:
#    scenario:
#      bizdate:
#        process:
          plugin: 
            type: scripts
            targets:
              - SCRIPT_NAME:
                result: success|error|canceled
                start time: YYYY-MM-DD HH:mm:ssZ|null
                end time: YYYY-MM-DD HH:mm:ssZ|null
                processing time: HH:mm:ss|null
```
